import type { OfflinePackage } from "@smritisetu/shared-types";
import {
  asha,
  daughter,
  grandson,
  son,
  home,
  festival,
  teaGarden,
  river,
  wedding,
} from "../assets/embeddedAssets";

export const LOCAL_DEMO_PATIENT_ID = "demo-aita";
export const LOCAL_DEMO_DEVICE_ID = "demo-device";
export const LOCAL_DEMO_TOKEN = "demo-local-device-token";

const now = () => new Date().toISOString();
const everyDay = [0, 1, 2, 3, 4, 5, 6];

/**
 * Aita's household, stored on the device when the backend cannot be reached.
 * Photos are embedded directly for rich offline display in My Memories,
 * Call Family, Who Is This, and Memory Lane.
 */
export function buildLocalDemoPackage(): OfflinePackage {
  const patientId = LOCAL_DEMO_PATIENT_ID;
  const generatedAt = now();

  return {
    packageVersion: 1,
    generatedAt,
    patient: {
      patientId,
      displayName: "Aita",
      preferredName: "Aita",
      age: 72,
      location: "Jorhat, Assam",
      preferredLanguage: "as",
      stateId: "AS",
      communityId: "assam.general",
      reducedMotion: false,
      largeText: true,
      audioGuidanceEnabled: true,
    },
    schedules: [
      {
        scheduleId: "demo-medicine",
        patientId,
        kind: "MEDICINE",
        titleKey: "myDay.kind.MEDICINE",
        titleEn: "Morning medicine",
        titleAs: "ৰাতিপুৱাৰ ঔষধ",
        detail: "With breakfast",
        critical: true,
        occurrences: [{ timeOfDay: "08:00", daysOfWeek: everyDay }],
        missedAfterMinutes: 30,
        snoozeMinutes: 10,
        version: 1,
        active: true,
        updatedAt: generatedAt,
      },
      {
        scheduleId: "demo-water",
        patientId,
        kind: "HYDRATION",
        titleKey: "myDay.kind.HYDRATION",
        titleEn: "Drink water",
        titleAs: "পানী খাওক",
        critical: false,
        occurrences: [{ timeOfDay: "11:00", daysOfWeek: everyDay }],
        missedAfterMinutes: 45,
        snoozeMinutes: 15,
        version: 1,
        active: true,
        updatedAt: generatedAt,
      },
      {
        scheduleId: "demo-lunch",
        patientId,
        kind: "MEAL",
        titleKey: "myDay.kind.MEAL",
        titleEn: "Lunch",
        titleAs: "দুপৰীয়াৰ আহাৰ",
        critical: false,
        occurrences: [{ timeOfDay: "13:00", daysOfWeek: everyDay }],
        missedAfterMinutes: 45,
        snoozeMinutes: 15,
        version: 1,
        active: true,
        updatedAt: generatedAt,
      },
      {
        scheduleId: "demo-walk",
        patientId,
        kind: "EXERCISE",
        titleKey: "myDay.kind.EXERCISE",
        titleEn: "Walk outside",
        titleAs: "বাহিৰত খোজ কাঢ়ক",
        critical: false,
        occurrences: [{ timeOfDay: "16:00", daysOfWeek: everyDay }],
        missedAfterMinutes: 60,
        snoozeMinutes: 20,
        version: 1,
        active: true,
        updatedAt: generatedAt,
      },
    ],
    contacts: [
      {
        contactId: "demo-nabanita",
        patientId,
        name: "Nabanita",
        relationshipEn: "Daughter",
        relationshipAs: "জীয়ৰী",
        phoneNumber: "+919000000001",
        photoUrl: daughter.uri,
        isPrimary: true,
        displayOrder: 1,
      },
      {
        contactId: "demo-bhaskar",
        patientId,
        name: "Bhaskar",
        relationshipEn: "Son",
        relationshipAs: "পুতেক",
        phoneNumber: "+917402059715",
        photoUrl: son.uri,
        isPrimary: false,
        displayOrder: 2,
      },
      {
        contactId: "demo-rishav",
        patientId,
        name: "Rishav",
        relationshipEn: "Grandson",
        relationshipAs: "নাতি",
        phoneNumber: "+919000000002",
        photoUrl: grandson.uri,
        isPrimary: false,
        displayOrder: 3,
      },
    ],
    memories: [
      {
        memoryId: "demo-nabanita",
        patientId,
        category: "MY_FAMILY",
        assetType: "PHOTO",
        titleEn: "Nabanita",
        titleAs: "নবনীতা",
        captionEn: "at home, in Jorhat",
        captionAs: "যোৰহাটৰ ঘৰত",
        storyEn: "Nabanita brings you red tea every evening and you talk about the garden.",
        storyAs: "নবনীতাই প্ৰতি সন্ধিয়া আপোনালৈ ৰঙা চাহ আনে আৰু আপোনালোকে বাগিছাৰ কথা পাতে।",
        personName: "Nabanita",
        relationshipEn: "Daughter",
        relationshipAs: "জীয়ৰী",
        mediaUrl: daughter.uri,
        consentId: "demo-consent",
        favourite: true,
        available: true,
        createdAt: generatedAt,
      },
      {
        memoryId: "demo-bhaskar",
        patientId,
        category: "MY_FAMILY",
        assetType: "PHOTO",
        titleEn: "Bhaskar",
        titleAs: "ভাস্কৰ",
        captionEn: "in the courtyard of the old house",
        captionAs: "পুৰণি ঘৰৰ চোতালত",
        storyEn: "Bhaskar learned to ride a bicycle in the courtyard of your old house.",
        storyAs: "ভাস্কৰে আপোনাৰ পুৰণি ঘৰৰ চোতালতে চাইকেল চলাব শিকিছিল।",
        personName: "Bhaskar",
        relationshipEn: "Son",
        relationshipAs: "পুতেক",
        mediaUrl: son.uri,
        consentId: "demo-consent",
        favourite: false,
        available: true,
        createdAt: generatedAt,
      },
      {
        memoryId: "demo-rishav",
        patientId,
        category: "MY_FAMILY",
        assetType: "PHOTO",
        titleEn: "Rishav",
        titleAs: "ঋষভ",
        captionEn: "at Bihu, in Majuli",
        captionAs: "মাজুলিত বিহুত",
        storyEn: "Rishav loves the pitha you make during Bihu.",
        storyAs: "ঋষভে বিহুত আপুনি বনোৱা পিঠা বৰ ভাল পায়।",
        personName: "Rishav",
        relationshipEn: "Grandson",
        relationshipAs: "নাতি",
        mediaUrl: grandson.uri,
        consentId: "demo-consent",
        favourite: false,
        available: true,
        createdAt: generatedAt,
      },
      {
        memoryId: "demo-asha",
        patientId,
        category: "MY_FAMILY",
        assetType: "PHOTO",
        titleEn: "Asha",
        titleAs: "আশা",
        captionEn: "together in the garden",
        captionAs: "বাগিছাত একেলগে",
        storyEn: "Asha and you walking together in the tea garden in the warm afternoon.",
        storyAs: "আশা আৰু আপুনি আবেলি চাহ বাগিছাত একেলগে খোজ কাঢ়ি থকা মুহূৰ্ত।",
        personName: "Asha",
        relationshipEn: "Wife",
        relationshipAs: "পত্নী",
        mediaUrl: asha.uri,
        consentId: "demo-consent",
        favourite: true,
        available: true,
        createdAt: generatedAt,
      },
      {
        memoryId: "demo-home",
        patientId,
        category: "MY_HOME",
        assetType: "PHOTO",
        titleEn: "Our house in Jorhat",
        titleAs: "যোৰহাটৰ আমাৰ ঘৰ",
        captionEn: "the house with the wooden verandah",
        captionAs: "কাঠৰ বাৰাণ্ডা থকা ঘৰটো",
        storyEn: "You planted the tulsi at the front of this house yourself.",
        storyAs: "এই ঘৰৰ আগত থকা তুলসী গছজোপা আপুনি নিজে ৰোপণ কৰিছিল।",
        mediaUrl: home.uri,
        consentId: "demo-consent",
        favourite: true,
        available: true,
        createdAt: generatedAt,
      },
      {
        memoryId: "demo-festival",
        patientId,
        category: "MY_FESTIVALS",
        assetType: "PHOTO",
        titleEn: "Bihu Celebration",
        titleAs: "বিহু উদযাপন",
        captionEn: "spring festival at home",
        captionAs: "ঘৰত বসন্ত উৎসৱ",
        storyEn: "Celebrating Rongali Bihu with songs, dhol, and traditional sweets.",
        storyAs: "গীত, ঢোল আৰু পৰম্পৰাগত পিঠাৰে ৰঙালী বিহু উদযাপন।",
        mediaUrl: festival.uri,
        consentId: "demo-consent",
        favourite: true,
        available: true,
        createdAt: generatedAt,
      },
      {
        memoryId: "demo-teagarden",
        patientId,
        category: "MY_PLACES",
        assetType: "PHOTO",
        titleEn: "Jorhat Tea Garden",
        titleAs: "যোৰহাটৰ চাহ বাগিছা",
        captionEn: "green hills in the morning",
        captionAs: "ৰাতিপুৱাৰ সেউজীয়া পাহাৰ",
        storyEn: "The fresh scent of morning tea leaves across the valley.",
        storyAs: "উপত্যকা জুৰি ৰাতিপুৱাৰ সতেজ চাহ পাতৰ সুবাস।",
        mediaUrl: teaGarden.uri,
        consentId: "demo-consent",
        favourite: true,
        available: true,
        createdAt: generatedAt,
      },
      {
        memoryId: "demo-river",
        patientId,
        category: "MY_PLACES",
        assetType: "PHOTO",
        titleEn: "Brahmaputra Sunset",
        titleAs: "ব্ৰহ্মপুত্ৰৰ সূৰ্যাস্ত",
        captionEn: "by the gentle river",
        captionAs: "নদীৰ পাৰত",
        storyEn: "Watching the golden sunset on the quiet banks of the Brahmaputra.",
        storyAs: "ব্ৰহ্মপুত্ৰৰ নিস্তব্ধ পাৰত সোণালী সূৰ্যাস্ত উপভোগ কৰা।",
        mediaUrl: river.uri,
        consentId: "demo-consent",
        favourite: false,
        available: true,
        createdAt: generatedAt,
      },
      {
        memoryId: "demo-wedding",
        patientId,
        category: "HAPPY_MOMENTS",
        assetType: "PHOTO",
        titleEn: "Family Wedding",
        titleAs: "পৰিয়ালৰ বিয়া",
        captionEn: "joyful celebration",
        captionAs: "আনন্দময় মিলন",
        storyEn: "All the family gathered together celebrating with joy and laughter.",
        storyAs: "আনন্দ আৰু হাঁহিৰে সকলো পৰিয়াল একত্ৰিত হৈ উদযাপন।",
        mediaUrl: wedding.uri,
        consentId: "demo-consent",
        favourite: true,
        available: true,
        createdAt: generatedAt,
      },
      {
        memoryId: "demo-kar-porokh",
        patientId,
        category: "MY_SONGS",
        assetType: "AUDIO",
        titleEn: "Kar Porokh",
        titleAs: "কাৰ পৰশ",
        captionEn: "Beloved Assamese song by Zubeen Garg",
        captionAs: "জুবিন গাৰ্গৰ প্ৰিয় অসমীয়া গান",
        storyEn: "Listening to Kar Porokh brings a wave of calm and happy musical memories.",
        storyAs: "কাৰ পৰশ গানটোৱে মনত শান্তি আৰু মধুৰ স্মৃতি জগাই তোলে।",
        mediaUrl: "kar_porokh",
        voiceUrl: "kar_porokh_audio",
        consentId: "demo-consent",
        favourite: true,
        available: true,
        createdAt: generatedAt,
      },
    ],
    difficultyProfiles: (
      [
        "MEMORY_MATCH",
        "ROUTINE_BUILDER",
        "WHO_IS_THIS",
        "MEMORY_LANE",
      ] as const
    ).map((gameType) => ({
      patientId,
      gameType,
      currentDifficulty: 2,
      hintLevel: 2,
      reasonCode: "BASELINE",
      explanation: "Starting from the level Aita has been playing comfortably.",
      modelVersion: "local-demo",
      evidenceSessionCount: 0,
      updatedAt: generatedAt,
    })),
    languagePack: {
      language: "as",
      version: 1,
      translations: {},
      audioPrompts: [],
    },
    gameConfig: {
      patientId,
      games: [
        { gameType: "MEMORY_MATCH", enabled: true, difficulty: 2, hintLevel: 2, previewSeconds: 6 },
        { gameType: "ROUTINE_BUILDER", enabled: true, difficulty: 2, hintLevel: 2 },
        { gameType: "WHO_IS_THIS", enabled: true, difficulty: 2, hintLevel: 2 },
        { gameType: "MEMORY_LANE", enabled: true, difficulty: 2, hintLevel: 2 },
      ],
      recommendedGameType: "MEMORY_MATCH",
      recommendationExplanation: "A gentle place to begin.",
    },
    contentPack: {
      stateId: "AS",
      stateName: "Assam",
      communityId: "assam.general",
      primaryLanguage: "as",
    },
  };
}
